# Generated by Django 3.2.18 on 2023-04-27 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe_userapp', '0003_auto_20230427_1603'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contactdb',
        ),
    ]
