# Generated by Django 3.2.18 on 2023-04-27 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe_userapp', '0004_rename_contact_contactdb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contactdb',
            new_name='contact',
        ),
    ]
