# Generated by Django 3.2.18 on 2023-04-28 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe_userapp', '0006_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='name1',
            new_name='name_d',
        ),
    ]
