# Generated by Django 3.2.18 on 2023-04-29 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe_userapp', '0007_rename_name1_register_name_d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='name_d',
        ),
    ]
