# Generated by Django 3.2.18 on 2023-04-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=10)),
                ('recipe_image', models.ImageField(default='null.jpg', upload_to='pic')),
                ('instruction', models.TextField(max_length=100)),
                ('ingredients', models.TextField(max_length=1000)),
            ],
        ),
    ]
