# Generated by Django 3.2.18 on 2023-04-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe_adminapp', '0002_alter_recipe_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instruction',
            field=models.TextField(max_length=2000),
        ),
    ]
